---
- hosts: all
  sudo: yes
  vars:
    mysql_root_password: changeRootPassword 
    public_user_password: changePublicPassword 

  tasks:
    - name: Install apt packages for git, nginx, and pip3
      apt:
        pkg: "{{item}}"
        state: present
      with_items:
        - git
        - nginx
        - python3-pip

    - name: copy the requirements file over
      copy:
        src: requirements.txt
        dest: /tmp/requirements.txt

    - name: pip install the required python3 libs (including uwsgi)
      pip:
        executable: pip3
        requirements: /tmp/requirements.txt

    - name: copy over nginx configuration
      copy:
        src: nginx.conf
        dest: /etc/nginx.conf

    - name: reboot nginx with the new configuration file
      service:
        name: nginx
        state: restarted

    - name: copy over the learningmachine data definitions.
      copy:
        src: learningmachine.sql
        dest: /tmp/learningmachine.sql

    - name: Create the learning machine database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: learningmachine
        state: present

    - name: Migrate table defs into the database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: learningmachine
        state: import
        target: /tmp/learningmachine.sql

    - name: Make the directories
      file:
        path: "{{item}}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0770
      with_items:
        - /var/app/learningmachine/
        - /var/log/learningmachine/
        - /var/www/learningmachine/static/
