---



- name: copy over nginx configuration
  template:
    src: lm_nginx.conf
    dest: /etc/nginx/sites-available/lm_nginx.conf
    owner: www-data
    group: www-data
    mode: 0550
  notify: restart nginx

- name: set up the symlink for the learning machine nginx config.
  file:
    path: /etc/nginx/sites-enabled/lm_nginx.conf
    src: /etc/nginx/sites-available/lm_nginx.conf
    state: link
  notify: restart nginx

- name: Create the learning machine database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: learningmachine
    state: present

- name: Make the directories
  file:
    path: "{{item}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0770
  with_items:
    - /var/app/learningmachine/
    - /var/log/learningmachine/
    - /var/www/learningmachine/

- name: Copy over the source and config files for the learning machine app
  copy:
    src: "{{item}}"
    dest: /var/app/learningmachine/{{item}}
    mode: 0660
    owner: www-data
    group: www-data
  with_items:
    - client_secret.json
    - lm.ini
    - login.py
    - model.py
    - view.py
    - tabledefs.py
    - handler_trigger.txt
  notify: update tables

- name: Copy over util scripts to handle deletions and ensuring table existence
  copy:
    src: "{{ item }}"
    dest: /var/app/learningmachine/
    mode: 0550
    owner: www-data
    group: www-data
  with_items:
    - make_tables.py

- name: Copy over the html and javascript static assets
  copy:
    src: static
    dest: /var/www/learningmachine/
    mode: 0660
    owner: www-data
    group: www-data


- name: set up the config template
  template:
    src: config.ini.template
    dest: /var/app/learningmachine/config.ini
    mode: 0660
    owner: www-data
    group: www-data

- name: Copy over the upstart learningmachine service script
  copy:
    src: learningmachine.conf
    dest: /etc/init/learningmachine.conf
    owner: www-data
    group: www-data
    mode: 0660
